export const searchIndex = [
  // /padroes/acessibilidade
  { term: "contraste", href: "/padroes/acessibilidade" },
  { term: "wcag", href: "/padroes/acessibilidade" },
  { term: "foco", href: "/padroes/acessibilidade" },
  { term: "aria", href: "/padroes/acessibilidade" },
  { term: "teclado", href: "/padroes/acessibilidade" },
  { term: "leitor de tela", href: "/padroes/acessibilidade" },
  { term: "skip link", href: "/padroes/acessibilidade" },
  { term: "reduced motion", href: "/padroes/acessibilidade" },
  // /fundamentos/animacoes
  { term: "easing", href: "/fundamentos/animacoes" },
  { term: "movimento", href: "/fundamentos/animacoes" },
  { term: "prefers-reduced-motion", href: "/fundamentos/animacoes" },
  // /fundamentos/cores
  { term: "paleta", href: "/fundamentos/cores" },
  { term: "pv-blue", href: "/fundamentos/cores" },
  { term: "pv-green", href: "/fundamentos/cores" },
  { term: "pv-yellow", href: "/fundamentos/cores" },
  { term: "swatch", href: "/fundamentos/cores" },
  { term: "hex", href: "/fundamentos/cores" },
  { term: "azul", href: "/fundamentos/cores" },
  { term: "amarelo", href: "/fundamentos/cores" },
  { term: "erro", href: "/fundamentos/cores" },
  // /fundamentos/tipografia
  { term: "poppins", href: "/fundamentos/tipografia" },
  { term: "escala", href: "/fundamentos/tipografia" },
  { term: "microtexto", href: "/fundamentos/tipografia" },
  // /fundamentos/layout
  { term: "grid", href: "/fundamentos/layout" },
  { term: "container", href: "/fundamentos/layout" },
  { term: "espaçamento", href: "/fundamentos/layout" },
  // /fundamentos/raios-sombras
  { term: "border-radius", href: "/fundamentos/raios-sombras" },
  { term: "sombra", href: "/fundamentos/raios-sombras" },
  { term: "elevação", href: "/fundamentos/raios-sombras" },
  // componentes
  { term: "card de serviço", href: "/componentes/service-card" },
  { term: "em breve", href: "/componentes/service-card" },
  { term: "tabs", href: "/componentes/controles" },
  { term: "chips", href: "/componentes/controles" },
  { term: "filtro", href: "/componentes/controles" },
  { term: "CTA", href: "/componentes/header" },
  { term: "métricas", href: "/componentes/hero" },
  { term: "botão", href: "/componentes/botoes" },
  { term: "rodapé", href: "/componentes/footer" },
  { term: "resumo de erros", href: "/componentes/error-summary" },
  { term: "erro", href: "/componentes/error-summary" },
  { term: "validação", href: "/componentes/error-summary" },
  // padrões
  { term: "navegação", href: "/padroes/navegacao" },
  { term: "menu", href: "/padroes/navegacao" },
  { term: "formulário", href: "/padroes/formularios" },
  { term: "campos", href: "/padroes/formularios" },
  { term: "dados e relatórios", href: "/padroes/dados-relatorios" },
  { term: "tabela", href: "/padroes/dados-relatorios" },
  { term: "feedback", href: "/padroes/feedback" },
  { term: "padrões", href: "/padroes" },
  // diretrizes várias
  { term: "anti-padrão", href: "/padroes/anti-padroes" },
];